plugin 'cocoapods-dev-env'
use_frameworks! :linkage => :static

platform :ios, '11.0'

source 'git@gitlab.corp.youdao.com:luna-ios-framework/youdaospecrepository.git'
source 'https://github.com/CocoaPods/Specs.git'


target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'
  
  pod 'YDCommon/YDDebug', :dev_env => 'parent'
  pod 'YDPlugin', :dev_env => 'parent'
  # 如果使用了登录功能，需要打开下边的库，否则手机号登录部分会报assert导致崩溃
  # pod 'NELoginEngine/Fake' , :dev_env => 'parent'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        if config.name == 'Release'
          # 解决release 时 c++ 的 assert仍然会崩溃的问题
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'NDEBUG=1']
        end
    end
  end
end